openapi: 3.0.0
info:
  title: Linked Data Import API
  version: v1
  description: Linked Data Import API

paths:
  /linked-data-import/start:
    post:
      operationId: startImport
      tags:
        - import, start
      description: Start the process of Linked Data Import
      parameters:
        - name: fileUrl
          in: query
          required: true
          description: The URL of the file to be imported from S3
          schema:
            type: string
        - name: contentType
          in: query
          required: false
          description: Content type of the file to be imported (e.g., application/ld+json, text/turtle). JSON by default.
          schema:
            type: string
      responses:
        '200':
          description: ID of Linked Data Import job instance started
          content:
            text/plain:
              schema:
                type: string
        '404':
          description: No file is found in S3
        '500':
          description: Internal Server Error

components:
  schemas:
    searchResourcesRequestDto:
      $ref: folio-modules/linked.data/searchResourcesRequestDto.json
    authoritySearchResponse:
      $ref: folio-modules/search/authoritySearchResponse.json
    importResultDto:
      $ref: kafka/importResult.json
