openapi: 3.0.0
info:
  title: Linked Data Import API
  version: v1
  description: Linked Data Import API

paths:
  /linked-data-import/start:
    post:
      operationId: startImport
      tags:
        - import, start
      description: Starts the process of Linked Data Import and returns ID of Import Job Instance
      parameters:
        - name: fileUrl
          in: query
          required: true
          description: The URL of the file to be imported from S3
          schema:
            type: string
        - name: contentType
          in: query
          required: false
          description: Content type of the file to be imported (e.g., application/ld+json, text/turtle). JSON by default.
          schema:
            type: string
        - name: defaultWorkType
          in: query
          required: false
          description: Default Work extra type - MONOGRAPH or SERIAL
          schema:
            $ref: defaultWorkType.json
      responses:
        '200':
          description: ID of Linked Data Import job instance started
          content:
            text/plain:
              schema:
                type: string
        '404':
          description: No file is found in S3
        '500':
          description: Internal Server Error

  /linked-data-import/jobs/{jobId}:
    get:
      operationId: getJobInfo
      tags:
        - import, job
      description: Returns information about Import Job by ID
      parameters:
        - name: jobId
          in: path
          required: true
          description: The ID of the Import Job Instance
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Import Job information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/jobInfo'
        '404':
          description: Job not found
        '500':
          description: Internal Server Error

  /linked-data-import/jobs/{jobId}/failed-lines:
    get:
      operationId: getFailedLines
      tags:
        - import, job
      description: Downloads CSV file with failed RDF lines for the specified job
      parameters:
        - name: jobId
          in: path
          required: true
          description: The ID of the Import Job Instance
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: CSV file with failed RDF lines
          headers:
            Content-Disposition:
              description: Attachment header for file download
              schema:
                type: string
                example: 'attachment; filename="failed-lines.csv"'
          content:
            text/csv:
              schema:
                type: string
                format: binary
        '404':
          description: Job not found
        '500':
          description: Internal Server Error

components:
  schemas:
    importOutputEventDto:
      $ref: kafka/importOutputEvent.json
    importResultEventDto:
      $ref: kafka/result/importResultEvent.json
    jobInfo:
      $ref: jobInfo.json

