openapi: 3.0.0
info:
  title: Linked Data Import API
  version: v1
  description: Linked Data Import API

paths:
  /linked-data-import/start:
    post:
      operationId: startImport
      tags:
        - import, start
      description: Starts the process of Linked Data Import and returns ID of Import Job Instance
      parameters:
        - name: fileUrl
          in: query
          required: true
          description: The URL of the file to be imported from S3
          schema:
            type: string
        - name: contentType
          in: query
          required: false
          description: Content type of the file to be imported (e.g., application/ld+json, text/turtle). JSON by default.
          schema:
            type: string
        - name: defaultWorkType
          in: query
          required: false
          description: Default Work extra type - MONOGRAPH or SERIAL
          schema:
            $ref: defaultWorkType.json
      responses:
        '200':
          description: ID of Linked Data Import job instance started
          content:
            text/plain:
              schema:
                type: string
        '404':
          description: No file is found in S3
        '500':
          description: Internal Server Error

components:
  schemas:
    importOutputEventDto:
      $ref: kafka/importOutputEvent.json
    importResultEventDto:
      $ref: kafka/result/importResultEvent.json
